### ISSUE TITLE
Checking the convergence of DPDS?

### ISSUE THREAD

**Issue by AminAvan** [XingqiuHe/DPDS#3]
Dear friend,
Thank you for sharing the code for your algorithm.

Could you please guide me on how I can check (e.g., print(something)) whether the DPDS is converging (or learned the optimal policy)? I tried to write the following code, but I don't think it provides a solid solution. I would really appreciate your help.

```
class ConvergenceDetector:
    def __init__(self, window_size=1000, threshold=1e-2):
        self.window_size = window_size
        self.threshold = threshold
        self.values = []
        self.converged = False
        self.std_on_mean = 0.0

    def update(self, value):
        self.values.append(value)
        if len(self.values) > self.window_size:
            self.values.pop(0)

        if len(self.values) == self.window_size:
            mean = np.mean(self.values)
            std = np.std(self.values)
            self.std_on_mean = abs(std / mean)
            if abs(std / mean) < self.threshold:
                print(f"std / mean: {abs(std / mean)} --- th {self.threshold}")
                self.converged = True

    def is_converged(self):
        return self.converged

def train(T): 
...
actor_loss_detector = ConvergenceDetector()
actor_loss_detector.update(actor_loss)
if actor_loss_detector.is_converged(): 
    print(f"DPDS has converged at iteration {timer}") 
    agent.save_model()
```

Thank you so much.
Regards,
Amin

**Comment by XingqiuHe** [comment]
Hi Amin,

Thanks for your interest in our work. Also sorry for the late reply, I was on vacation for the past few days.

It has been over a year since I worked on this, so I don't remember some of the details very clearly. From what I recall, only the critic loss would converge, while the actor loss kept increasing. You can monitor the changes of the recorded variables in real time using TensorBoard (I highly recommend you try TensorBoard as it provides a very illustrative view on the changing trends of various variables). 

I also spent a lot of time investigating why the actor loss didn’t converge, but I never arrived at a definitive conclusion. It might be because I used the average reward instead of the discounted reward. 

Although the actor loss didn’t converge, the corresponding AoI and power consumption did converge, so the impact on the algorithm's effectiveness wasn’t significant.

Xingqiu

**Comment by AminAvan** [comment]
Dear Xingqiu,

Thank you very much for your kind response and the informative explanations. I greatly appreciate your assistance.

Regards,
Amin
